// <auto-generated />
namespace WindowsFormsApplication1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addingDBsFirstTime : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addingDBsFirstTime));
        
        string IMigrationMetadata.Id
        {
            get { return "201607020419478_addingDBsFirstTime"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
